import type { Env } from "../env";

/**
 * Env-driven feature flags. `FEATURES` (wrangler.toml [vars]) is a comma-separated list of
 * enabled keys, e.g. "refund_netting,bulk_import". A behaviour ships behind a flag so it can be
 * disabled with one var edit + redeploy (instant rollback) with no data change. Single tenant
 * today, so flags are env-global; per-tenant gating can move to `profiles` later without changing
 * call sites (they only see `featureOn(env, key)`).
 */
export const FEATURE_KEYS = [
  "refund_netting",
  "refund_netting_v2", // #258 (Wave 1): net a refund ONLY against the specific DEDUCTIBLE expense it reverses (refund_for_txn_id), capped at that expense; unlinked/personal refunds are position-neutral. Fixes v1's global netting that subtracted personal reimbursements from unrelated deductions (under-claim). Separate flag from refund_netting (which is ON in prod) so this money-output change flips deliberately. OFF ⇒ v1 global netting ⇒ byte-identical.
  "income_dedupe",
  "income_statement_multi", // Feature A1 increment 2 (#304): the multi-employer income-statement ENGINE, gated INSIDE the existing 'payslip' case of classifyAndRoute (doc_type stays 'payslip' — no classifier change, doesn't touch the shipped income_statement_upload button). ON ⇒ decomposeIncomeStatement loops each FINALISED employer → one salary_payg row at the PRINTED Total gross (leave already inside it) + capture-only employment_lump_sum rows; SG dropped, RESC/RFB non-assessable; an income-table supersede guard replaces prior per-period payslip/manual salary rows for the same employer+FY (no double-count). OFF ⇒ today's single-employer extractPayslip path VERBATIM ⇒ byte-identical. Separate flag from income_statement_upload so the validated button + the unvalidated engine roll out independently.
  "income_statement_upload", // Feature A1 (#304): an "Upload income statement" button on the Income page that routes a PDF/photo of an ATO income statement / PAYG payment summary through the EXISTING documents-upload → classify → extractPayslip → recordIncome seam (salary_payg), so the user stops hand-keying salary. Reuses the proven payslip extractor + the APP-8 consent gate; extracted rows land needs_review for confirmation + surface via IncomeDedupe so they don't double-count a matching bank credit. Additive UI only (no server/routing change — the payslip path already exists). OFF ⇒ no button ⇒ byte-identical. (Multi-employer array extraction is the next increment.)
  "asset_defaults",
  "asset_life_default", // Bug fix: a div40 (plant) asset saved with NO effective life is persisted as null, which rollSchedule turns into a $0 depreciation schedule (life ?? 0 → `if (life<=0) break`). ON ⇒ createAsset resolves the rulepack/merchant-hinted default (else legacy 5y) for a blank div40 life so it actually depreciates. MONEY-OUTPUT (raises depreciation for the silent-zero case) ⇒ flip deliberately. OFF ⇒ binds the raw null (today's buggy behaviour) ⇒ byte-identical. Prereq for the Assets-form label-derived-life simplification.
  "bulk_import",
  "deductibility_review",
  "guide_me",
  "onboarding_checklist", // #246 (Wave 3): a situation-derived "bring these in" evidence checklist on the Dashboard (which accounts/statements/docs to add + WHY, with completion). OFF ⇒ the card isn't rendered ⇒ byte-identical.
  "journey_spine", // #247/#244 (Wave 3): a persistent breadcrumb of the 6 stops (Set up→Bring in→Sort→Check→Position→File) in the app shell — current stop highlighted, data-aware badges from progress. OFF ⇒ not rendered ⇒ byte-identical.
  "categorise_v2", // #253 (Wave 3): simplify TxnDetail to one primary Category decision + adaptive Confirm/Save, with ATO label / property / refund / date tucked behind an "Add detail" disclosure (auto-opened when detail exists). OFF ⇒ all fields inline as before ⇒ byte-identical.
  "txn_bulk_edit", // #252 (Wave 3): multi-select + the BulkBar on the Transactions page (where search/filter/group isolate a merchant's look-alikes) so already-categorised lines can be re-bucketed/attributed in one audited, undoable batch. OFF ⇒ no checkboxes/bar ⇒ byte-identical.
  "claim_review",
  "txn_scan", // #256 (Wave 2): pre-handoff "double-check my transactions" scan — deterministic over-claim + missed-deduction review surfaced on Reports + a non-blocking download gate. Read-only/additive (proposals only, no auto-claim). OFF ⇒ /api/scan 404s, no UI, byte-identical.
  "txn_scan_v2", // Audit #387/#288 (pattern-aware scan): extends the deterministic double-check with category-"check" completeness prompts ($0 impact, no one-tap — the user must enter data): (1) salary >= $50k with < $300 of counting work deductions -> a proactive prompt that quotes the tenant's authored occupation guide ("as a nurse, people commonly claim..."); (2) salary present but no WFH hours recorded; (3) per-rental completeness — deductions-but-no-rent (income must be declared), rent-but-no-expenses, linked-loan-but-no-interest-summary. Facts are only assembled (4 extra queries) when the flag is on; runScan without facts is byte-identical v1. Requires txn_scan. OFF => no "check" findings => byte-identical.
  "inline_claim", // Owner testing feedback (2026-07-03): a compact CLAIM control on the review surfaces so lines can be resolved without the full editor — a "Claim…" select (donation D9 · deductible in full · deductible N% work-use · not deductible) on BOTH the inline row editor and the BulkBar (mass edit). The % path extends setDeductibility with businessUsePct computing the claimable amount PER ROW (amount × pct, resolveByLabel's proven expression) — never one flat amount across a batch. Donation = ato_label 'donation' correction (audited/undoable) + confirmed_deductible at full amount. Everything routes through the existing audited seams (correctBatch + /api/deductibility, which requires deductibility_review). OFF ⇒ no claim controls, setDeductibility callers pass no pct ⇒ byte-identical.
  "position_confirmed_range", // #255 (Wave 3): surface a CONFIRMED-end taxable position alongside the existing (tracked, optimistic) one, so the Reports headline reads as a range confirmed→tracked instead of presenting the optimistic figure as THE position. ADDITIVE display output (taxable_position_confirmed_cents) — the existing taxable_position_cents is untouched. OFF ⇒ field omitted ⇒ byte-identical.
  "position_excludes_nondeductible",
  "position_excludes_property_undetermined", // #254 (Wave 1): deny-by-default for property-bucket spend that can't yet land in an income-producing property — no property_id, or a property whose use_status isn't 'rented'/'genuinely_available_for_rent'. Mirrors the payg 'undetermined' deny. Separate flag (NOT folded into position_excludes_nondeductible, which is already ON in prod) so the money-output change flips deliberately. OFF ⇒ the SQL marker is the literal "0" ⇒ byte-identical.
  "accountant_pass",
  "wfh_car_methods",
  "car_methods", // #245 (Wave 3): source car cents-per-km km from the dedicated car_inputs table (split out of work_use_inputs) so WFH and car are separate typed units. OFF ⇒ car km read from the legacy work_use_inputs.car_work_km column ⇒ byte-identical. The 0061 backfill seeds car_inputs from the legacy column so flag-ON is identical for existing data.
  "wfh_generate_diary",  // 0059 (Part 1): emit a generated WFH diary section in the accountant CSV. OFF by default — flag-OFF + own-record paths keep the legacy CSV byte-identical.
  "loan_split",
  "attribution_engine", // 0032-0034: sum transaction_attributions for the position (payer≠claimant, ownership split). OFF in prod until validated.
  "cgt_engine",         // 0037 (#138): add net capital gain (shares/crypto/property disposals; 50% discount; loss offset) to the position. OFF in prod until validated.
  "ess_engine",         // 0038 (#141): add assessable ESS discount (taxed-upfront / deferral) to the position; startup concession defers to CGT. OFF in prod until validated.
  "gst_bas",            // 0039 (#137): indicative BAS position (output GST − input credits) for GST-registered businesses. SEPARATE from income tax. OFF in prod until validated.
  "car_logbook",        // 0040 (#142): logbook-method car deduction vs cents-per-km (informational). OFF in prod until validated.
  "trust_distributions",// 0041 (#139): add assessable trust distributions (character retained) to the beneficiary's position. OFF in prod until validated.
  "smsf_engine",        // 0042 (#140): per-SMSF fund position after ECPI (separate taxpayer); keeps fund income out of the member's personal headline. OFF in prod until validated.
  "apply_to_siblings",  // Sort epic S1: "edit one line → update its look-alikes" (+ learn a rule) off the normal edit path. No position math. OFF until the S2 UI ships.
  "loan_interest_v2",   // Sort epic S4/S5 (#157): evidence-first loan interest (lender/statement actual → property position), retiring the per-line loan_split. Capture-only in S4; report wiring in S5. OFF until validated.
  "ask_quillo",         // C1: single-turn grounded tax-Q&A — answers a free-text question from the user's OWN ledger (consent + budget gated, GENERAL-INFO, no refund/rates). Multi-turn chat is a later epic.
  "accountant_schedule",// #179/#181: itemised accountant schedule CSV (per-txn lines, engine schedules, NOT-CLAIMED, substantiation) replaces the thin summary CSV at format=csv. OFF in prod until validated.
  "ask_actions",        // Ask Quillo C3: FY txn digest in the Ask prompt + model-PROPOSED one-click fixes (set_deductibility / recategorise / add_rule). Propose→confirm→execute via the EXISTING write endpoints — never autonomous. Applying a deductibility card needs deductibility_review ON. OFF ⇒ Ask byte-identical.
  "advisory_layer",     // Savings & Opportunities (#182–184): annualised spend run-rate + deterministic recurring-bill/subscription detection + FACTUAL opportunity nudges + the "Save" surface. No LLM, no partners, no PII egress, no projections/benchmarks (src/lib/advisory.ts). OFF ⇒ no read/write path, byte-identical.
  "advisory_partners_energy", // Advisory Phase 2 (docs/advisory-phase2-partners.md): the Tier-1 energy partner CTA on advisory opportunities + the create-referral path. Identity/data-model scaffold ships flag-OFF (Slice 1); no consumer CTA, no live partner, no PII egress until this is ON *and* legal sign-off (§5) lands. OFF ⇒ byte-identical.
  "franking_gross_up",  // Phase 3a (s207-20): gross franked dividend/distribution franking credits INTO assessable income (the credit is also a refundable offset, out of scope). ADDS to taxable_position. OFF ⇒ byte-identical.
  "super_deduction",    // Phase 3a (s290-150): personal-deductible super contributions (type='personal_deductible' only — never employer SG) reduce assessable income up to the concessional cap. SUBTRACTS from taxable_position. OFF ⇒ byte-identical.
  "partnership_distributions", // Slice E: a partner's share of partnership net income (character retained, ITAA36 Div 5) feeds the personal position like a trust distribution — same trust_distributions table, source_kind='partnership' (migration 0056). ADDS to taxable_position. OFF ⇒ byte-identical.
  "mf_components",      // Slice B: managed-fund (AMMA) distribution component split. A managed_fund_distribution row's ordinary income lands in gross_cents; its capital-gain components are materialised into the CGT engine (50% discount + loss-offset); the AMIT cost-base amount stays out of the position (defer nudge). v1: AUD-only + personal-only. Gated on flag AND presence-of-components, so OFF or a no-components row ⇒ byte-identical.
  "ai_edit_feed",       // Phase 4: the ai_edits audit/undo log (migration 0057) + its "AI changes — undo" feed (GET /api/ai-edits, POST /api/ai-edits/undo). Read/undo surface for the audited entity-write path. OFF ⇒ feed endpoints 404 ⇒ byte-identical.
  "ask_actions_v2",     // Phase 3: extended chat write tools — model PROPOSES create/edit of property|entity|person|rule; user confirms a card; execution routes through the audited DO path (aiWriteEntity → ai_edits + audit_log), idempotent per action_id, NEVER autonomous. Requires ai_edit_feed for the undo backstop. OFF ⇒ no entity-write proposals ⇒ byte-identical.
  "chat_nav",           // Phase 2: the chat agent may propose navigating to an allowlisted SPA route (navigate field on give_answer) + receives the user's current page as grounding. Rendered as a "Take me to …" button (never a silent jump); route enum + server re-check. OFF ⇒ no navigate emitted/honoured + no page line ⇒ byte-identical.
  "floating_chat",      // Floating "Ask Quillo" bubble (assistant-ui headless runtime + our tokens): relocates the embedded Dashboard chat into a persistent portal-mounted widget that survives navigation. Reuses the existing /api/chat + proposed-action path; no engine/position change. OFF ⇒ the widget renders nothing ⇒ byte-identical.
  "jurisdiction_period",// UK epic stop 1: the tax period is resolved from profiles.jurisdiction via a JurisdictionDescriptor (src/lib/jurisdiction.ts) instead of a hardcoded Jul–Jun. MASTER GATE: OFF ⇒ always the AU descriptor regardless of the stored code ⇒ byte-identical. ON ⇒ a tenant with jurisdiction='UK' gets the Apr 6 – Apr 5 period (de-hardcodes fyBounds / currentFyStartYear / fyForDate / fyStartYearOf + the queries.ts SQL month gate). No currency/rule-pack/engine change this stop.
  "currency_base",      // UK epic stop 2: de-anchor the money model from AUD to the tenant's BASE currency (descriptor.baseCurrency — AU 'AUD', UK 'GBP'). Routed through baseCurrencyOf(env, descriptor) (src/lib/jurisdiction.ts), the single chokepoint every base read uses. The FX layer converts foreign amounts to the base (fx.ts toBaseCurrency); amount_aud_cents now means "base-currency cents" (legacy name kept — the ~17 SUM(COALESCE) sites are currency-agnostic). OFF ⇒ base forced to 'AUD' everywhere regardless of jurisdiction ⇒ byte-identical. ON + AU profile ⇒ base='AUD' ⇒ still byte-identical. (The SPA display follows the payload's base_currency, NOT this flag — money() defaults to '$'/'en-AU' when base_currency is absent/'AUD'.)
  "record_credit_income", // #130: a one-click "Record as rental income" button on a rent CREDIT tagged to a property (TxnDetail) — the per-txn equivalent of the Clarify group income answer (recordTxnAsIncome → recordIncome + matched_income_id link, single-count). OFF ⇒ the button is hidden + POST /api/transactions/:id/record-income 404s ⇒ byte-identical.
  "phi_extras_tracker", // Private Health Extras Tracker (engagement, NOT a tax output): track per-category private-health EXTRAS limits + spend-to-date against the reset date ("use it before you lose it"), with manual policy/limit entry, a detected `phi_extras` advisory opportunity, and an in-app reset reminder. Reads/writes the phi_policy/phi_limit/phi_benefit_usage tables (0062), gated everywhere by this flag. Display/categorisation only — never feeds report.ts; taxable_position_cents is byte-identical ON vs OFF (persona golden). OFF ⇒ no read/write path, no UI, byte-identical.
  "billing", // Usage-based wallet billing: free to join + a free credit allowance, then the user pays their actual AI cost + a tiny margin from a pre-paid credit balance (Stripe top-up). Gates a model call on a positive balance and debits each call (billableE4). OFF ⇒ no gate, no debit, no grant ⇒ byte-identical (today's free-for-testers behaviour). Activate alongside the STRIPE_* secrets.
  "quillo_fee_deduction", // Auto-record each PAID Stripe top-up (kind='topup', not the free grant) as the customer's own deductible expense — "cost of managing tax affairs" (s25-5, ATO label D10): a bucket='payg', ato_label='D10', deductibility='confirmed_deductible' receipt row, written inside creditWallet's idempotency guard (one row per Stripe session). MONEY-OUTPUT change (it raises total_deductions_cents / lowers taxable_position_cents). OFF ⇒ no fee row written ⇒ byte-identical. Requires `billing`.
  "phi_provider_directory", // #314 (interim, until NHSD/SD-207047): replace the static Healthdirect "find a provider" link on Extras with an in-app, opt-in list of nearby providers (Geoapify Places, server-proxied + 24h KV cache). FACTUAL/neutral only — no ranking/commission/fund-status claim; only postcode+service-type leave Quillo (no PII). Same /api/phi/providers seam + neutral shape NHSD later drops into. OFF ⇒ today's static link, no route, byte-identical.
  "phi_tax_inputs", // PHI annual-statement capture → MLS/rebate DEFER-NUDGE (sibling of the Div 293 nudge in readiness.ts). Captures phi_statement (0062) + a "income near the MLS threshold and no hospital cover on file — confirm with a registered tax agent" nudge. NEVER a computed $ amount and NEVER summed into taxable_position_cents (rebate/MLS stay reference-only per CLAUDE.md). Held OFF pending owner sign-off (needs-decision). OFF ⇒ no statement capture, no nudge, byte-identical.
  "clarify_direction_guard", // #341: make the Clarify multi-item flow direction-aware. A merchant group can be MIXED (credits + debits). OFF (today): mixed groups offer ONLY spend answers, and 'ignore'/an expense bucket apply to the WHOLE group — so income credits get silently dropped from the income table (ignore) or converted to an expense (bucket), understating tax. ON: mixed groups also offer the income answers (recorded via the already-direction-safe recordCreditAsIncome), and ignore/bucket apply to DEBITS only (credits left to be recorded as income / re-surface next scan). MONEY-OUTPUT change (it changes what lands in the income table). OFF ⇒ byte-identical (unit golden #341 in check-units.ts asserts ON offers the income answers + OFF is unchanged; the ignore/bucket handlers mirror the already-tested capital-handler direction guard). All 10 personas stay green because they don't set the flag.
  "grouped_review", // #342: the "Needs review" tab groups its lines by merchant into collapsible rows ("5× Coles") with a one-tap 'select all in group' that feeds the existing BulkBar (categorise the whole look-alike set at once), plus the receipt/bank-line kind filter Inbox had but ReviewView dropped. Pure IA/UI over the SAME review list + BulkBar seam — no data-model or position change. OFF ⇒ the flat review list exactly as before ⇒ byte-identical.
  "txn_inline_edit", // #343: a per-row "Edit" affordance on the review list opens an INLINE category (+ property) editor that saves via the existing audited correctBatch seam and surfaces the existing Undo toast — recategorising a single line WITHOUT the full-page navigation to TxnDetail (kept reachable via "Full editor →" for refund-linking / dates / attribution). No data-model/position change. OFF ⇒ no Edit button, rows behave exactly as before ⇒ byte-identical.
  "accountant_xlsx", // Accountant-handoff upgrade Phase 1: a multi-tab .xlsx workbook (one worksheet per schedule section, Summary first) at /api/report?format=xlsx — the SAME AccountantSchedule the CSV uses, re-projected (scheduleToXlsx, src/lib/xlsx.ts via fflate.zipSync, workerd-safe). Requires accountant_schedule (the itemised schedule must be built). Presentation-only — no engine/migration change. OFF ⇒ format=xlsx 404s, CSV path untouched ⇒ byte-identical.
  "readiness_audit_v2", // Mission-audit #7/#8 (safety + completeness): extra filing-readiness findings — a "rented property with $0 rent but deductions claimed" review flag (holding costs only deductible while genuinely available for rent — over-claim/audit safety), an "occupation not set" completeness flag (occupation drives which deductions Quillo can suggest), and an "confirm your ESS discount + taxing point" info nudge. All defer-to-agent / GENERAL-INFO. OFF ⇒ no new findings ⇒ byte-identical.
  "partnership_losses", // Mission-audit #10 (correctness): a PARTNERSHIP loss share flows through to the partner and reduces their income — but partnershipTotals reused the trust summariser, which floors every distribution at 0 (correct for trusts, whose losses are trapped), silently dropping partnership losses. ON ⇒ partnership distributions allow negative amounts (the loss reduces the indicative position); a Div 35 non-commercial-loss defer note applies. Requires partnership_distributions. Trusts still floor at 0. MONEY-OUTPUT ⇒ OFF ⇒ floored as today ⇒ byte-identical.
  "accountant_schedule_v2", // Mission-audit handoff fixes (#5/#3b): add two informational sections to the accountant schedule — a LOAN REGISTER (per loan × property: balance, rate, deductible %, interest, evidence source, statement) with an apportionment >100% warning so an agent can verify negative-gearing interest and over-allocation is caught; and an "FX — Excluded" list of foreign-currency income/spend that has no AUD conversion (silently dropped from every total today). Both informational (no tie-back). Requires accountant_schedule. OFF ⇒ the schedule is byte-identical.
  "carryforward_position", // Feature B2 (#71): apply prior-year ORDINARY tax losses (carried in from a CONFIRMED NOA via fy_carryovers.prior_year_tax_losses_cf_cents) to the indicative taxable position. A NOA's carried-forward tax loss is a CUMULATIVE running balance, so the LATEST confirmed NOA (max target_fy ≤ the report FY) is authoritative — not a sum (mirrors the B1 capital-loss single-active rule). The loss offsets ONLY positive income (Math.min(loss, max(0, pre-loss position))) so it can't push the position below zero; any unused remainder stays carried (not modelled further). MONEY-OUTPUT — flip after review. OFF ⇒ 0 applied ⇒ byte-identical.
  "txn_drawer", // Slice 6 (structural simplification): TxnDetail becomes one decision — the primary column is Category + the inline property selector (+ "Record as rental income") + Save; ATO label, date, refund-link, reimbursement, AttributionPanel, QuickBooks push, Delete and correction history all fold into ONE "More options" <details> that REPLACES both of today's disclosures (the categorise_v2 "Add detail" and the apply_to_siblings "Advanced"). The drawer auto-opens on the FULL detailRelevant condition (existing ATO label · undated · property bucket · a refund_netting_v2 refund) so a dated supplier refund's link picker is never buried (a silent deduction-netting money bug). Income-record flow stays synchronous (property → Save → canRecordIncome). Does NOT use the shared CategoryPicker. OFF ⇒ today's inline fields + dual disclosures, rebuilt from the same field consts ⇒ byte-identical.
  "guidance_v2", // Slice 7 (guidance consolidation, 4 surfaces → 2): the JourneySpine becomes the SINGLE ambient guidance surface — the 6 journey stops + badges, PLUS the merged-in next-action CTA + one-line summary (ported from NextActionBar, incl. its isError→QueryError+retry guard and the done-state copy) + an undated badge on Position + the per-tab "?" guide (reuses TabGuide, placed outside the spine's overflow so it isn't clipped). When ON, App renders Coachmarks + this enhanced spine (no separate NextActionBar/TabGuide row); the FySwitcher is re-homed above it. Gated separately from journey_spine (which stays ON and renders the UN-enhanced spine) so the CTA/badge never double-render. OFF ⇒ today's NextActionBar + TabGuide row + journey_spine spine, verbatim ⇒ byte-identical.
  "checklist_v2", // Slice 8 (guidance consolidation): fold the SetupChecklist "bring these in" evidence items into the per-FY ChecklistCard as one unified checklist (evidence section above the backend tasks), and suppress the standalone SetupChecklist mount. Reuses SetupChecklist verbatim via an `embedded` prop (same 4-query derivation, QueryError guard, auto-hide, localStorage marks, GENERAL-INFO line) so nothing is reimplemented. Gated by onboarding_checklist AND checklist_v2. OFF ⇒ the standalone SetupChecklist + separate ChecklistCard render exactly as today ⇒ byte-identical.
  "mobile_bottom_tabs", // Slice 12 (mobile IA): a fixed bottom tab bar on <lg screens — Home · Bring in · Sort (with the needs-review badge) · Position · More (opens the existing drawer). Reuses the GROUPS routes + the shared needsReview count; the desktop sidebar is untouched. Adds bottom padding to the main content only when ON. OFF ⇒ no bar, no padding ⇒ byte-identical.
  "nav_disclosure", // Slice 13 (nav IA): collapse the secondary sidebar groups (Save · Connections · Partner · Platform) into one "More" <details> above Settings; the journey stops (Bring in · Sort · Check · Position · File) + Dashboard stay expanded and every route stays one click away (Check/Reconcile stays primary). OFF ⇒ today's flat group list ⇒ byte-identical.
  "adaptive_dashboard", // Slice 14 (dashboard IA): hide the "By property" / "By category" breakdown panels entirely when they have no rows (instead of rendering an Empty state), so a salary-only user isn't shown empty property tables. Display-only — report.ts/ledger-totals.ts untouched. OFF ⇒ the Empty-state panels render as today ⇒ byte-identical.
  "asset_class_defaults", // Slice 11 (calculator de-densification, requires asset_life_default): the Assets form offers "Motor vehicle (Div 40)" as a first-class option (maps to asset_class=div40_plant + is_car=1, replacing the orphan is_car checkbox), the list shows a "Car" badge, and the effective-life field is de-emphasised as optional ("we use the ATO standard life if blank" — resolved server-side by asset_life_default). Presentation/mapping only — the create payload keeps the same fields (div40_plant + is_car + optional effective_life). OFF ⇒ today's flat class dropdown + separate car checkbox + plain life field ⇒ byte-identical.
  "wfh_hours_simple", // Slice 10 (calculator de-densification): WorkMethodsCard leads with ONE "Hours worked from home this year" field; the days/week + working-weeks inputs move into a collapsible "estimate from days × weeks" helper whose Apply just FILLS the hours field (one-way, mirroring the old onDays: derives hours, keeps diary weekdays in step, leaves hours non-touched so a live diary still drives them). The save payload is UNCHANGED (wfh_days_per_week/weeks still persist for the diary pre-tick; wfh_hours=null still emitted when the diary drives). OFF ⇒ today's three auto-deriving fields ⇒ byte-identical.
  "attribution_labels", // Slice 9 (calculator de-densification): AttributionPanel presentation-only polish — group the deduction-provision <select> into optgroups (Salary/work · Capital asset · Working from home · Private), promote the per-row claimed amount to a prominent "This costs you $X" badge, and red-border the rows when the attributed shares sum >100%. Save payload UNCHANGED (same provision values). OFF ⇒ flat select + plain claimed-amount line + no red border ⇒ byte-identical.
  "noa_capture", // Feature B1 (#71/#304): upload an ATO Notice of Assessment to CLOSE a tax year off. Adds doc_type 'notice_of_assessment' + extractNoticeOfAssessment; a NOA classifies then captures a DRAFT fy_carryovers row (no money written). The user confirms in Filing → the server writes net capital losses → capital_loss_carryins (flows through the already-wired cgt.ts offset), opening depreciation → depreciation_opening_balances (still capture-only), reference facts (HELP/MLS/franking) → fy_carryovers, and sets fy_signoff.status='closed_with_noa'. Confirm is a user action; the WRITE is money-output on the CGT position (same mechanism as a manual carry-in). OFF ⇒ the NOA case falls through to file-for-review, no NOA UI, no carry-over write ⇒ byte-identical. Prior-year TAX losses are captured but only applied to the income position by B2 (carryforward_position).
  "dep_method_lock", // Audit wave 1 (PR-3): enforce Div 40's one-election-per-asset rule (s 40-65 — diminishing value XOR prime cost, locked once used). assets.method was only \"locked\" by a schema comment; computeDepreciation's UNIQUE(asset_id,fy) upsert silently rewrote the whole schedule under a changed method. ON ⇒ recomputing an asset whose earliest schedule row was materialised under the OTHER elected method throws `method_locked` (API → 409 with GENERAL-INFO copy) unless the caller passes an explicit override (override_method_lock: true), which re-rolls AND writes a `depreciation_method_override` audit_log row. Class-driven outcomes (immediate, pools, div43, the second-hand lockout) are NOT elections and never conflict. OFF ⇒ the old silent re-roll ⇒ byte-identical.
  "integrity_nudges", // Audit wave 1 (PR-2): four extra defer-to-agent readiness nudges keyed to rule-pack REFERENCE values — (1) franking credits above the $5,000 small-shareholder boundary → 45-day holding-rule review nudge (below it → an info note that the exemption generally applies; holding periods are NEVER computed); (2) foreign tax paid above the $1,000 FITO de-minimis → offset-limit review nudge (the existing sub-$1k info wording is sharpened to mention the de-minimis); (3) rideshare-likely business income with no GST registration → Div 144 first-dollar registration review nudge (the $75k threshold does not apply to ride-sourcing); (4) non-concessional super contributions above the reference NCC cap → bring-forward/TSB review nudge. All GENERAL-INFO + defer; no $ computation, no position change. OFF ⇒ the new signals are never populated ⇒ findings byte-identical.
  "payg_express", // Audit wave 2 (PR-6): single-PAYG simplified surface. getSituation attaches payg_express_eligible (pure test: one self person; only individual/employment entities; no properties, business/rental activities, or CGT assets) ONLY when this flag is on — off ⇒ field omitted ⇒ situation payload byte-identical. The SPA hides the Assets nav item (sidebar + mobile More drawer render from the same filtered GROUPS) for eligible tenants; the 6-stop spine is untouched and eligibility self-heals when a property/business is added. Display-only — no report/data-model change.
  "trading_stock", // Audit wave 4 (PR-8, migration 0068): s 70-35 trading stock for goods-selling sole traders. One row per business x FY (opening_cents/closing_cents/valuation_basis); report.ts adds the signed adjustment (closing - opening) to the personal position for the entity_id-NULL (sole-trader) row ONLY — entity-scoped rows are captured but stay out (separate taxpayer). GET/POST /api/trading-stock 404 when off; audited DO upsert setTradingStock; accountant-schedule section + a valuation-basis defer nudge ride on the report field (which only exists when this flag is on). MONEY-OUTPUT — flip after review; persona golden (e-commerce sole trader) in the same PR. OFF => no field, no route, byte-identical.
  "non_cash_income", // Audit wave 4 (PR-9, owner-approved): assessable NON-CASH BUSINESS income (barter / gifted products received in the course of a business, assessable at market value — IT 2668). New income_type `non_cash_business`, assessable BY CONSTRUCTION (NON_ASSESSABLE_INCOME_TYPES is a denylist, so the engine needs zero change); the flag gates CREATION in recordIncome (400 when off), so OFF => no rows can exist => byte-identical. `non_cash_benefit` stays capture-only for personal/hobby gifts (its defer nudge now points business users at the new type). Income-page option only rendered when on. MONEY-OUTPUT — flip after review; influencer persona golden in the same PR.
  "grouped_review_v2", // Review-flow wave 3: cluster the merchant-grouped review list by the SERVER's normalised groupKey (clarify.ts — strips dates/reference numbers) instead of the exact merchant string, so near-identical lines ("RSL ART UNION 123456" / "…123457") collapse into ONE group with a single select-all-in-group checkbox instead of fragmenting into singletons. The transactions GET attaches group_key per row ONLY when this flag is on (OFF ⇒ field omitted ⇒ byte-identical payload); GroupedList keys on it (null key ⇒ row id ⇒ stays a singleton, never a junk group) and the grouped view gains the page-level "select all" the flat view already had. Presentation-only over the same review list + BulkBar — no data-model or position change. Requires grouped_review to render the grouped list at all. OFF ⇒ legacy exact-string grouping ⇒ byte-identical.
  "bulk_confirm", // Review-flow wave 2: a "Confirm as-is" action on the BulkBar that accepts the AI's CURRENT category for the whole selection and clears it from review in one audited batch (TaxAgent.confirmBatch) — the batched form of the per-row "Confirm ✓" (a self-correction to the row's own bucket), previously impossible in bulk because Apply requires picking a NEW category. Rows with no/'unknown' bucket are skipped. Position-neutral (needs_review rows with a bucket already count) — it only clears the review flag; deductibility is untouched. Not undoable (nothing changes but the review status; re-opening a row re-enters review), like the single-row confirm. OFF ⇒ no button + the /api/confirm/batch route 404s ⇒ byte-identical.
  "cgt_parcel_method", // Audit wave 4 (PR-10, migration 0069): record WHICH parcel-selection basis a CGT disposal used — cgt_events.method (NULL = specific identification, today's implicit semantics of the manually-entered cost base | 'fifo'). RECORD-KEEPING + DISPLAY ONLY: cgt.ts never reads it (auto-computing FIFO cost bases would be a separate money-output feature needing its own flag/golden). The API selects/accepts the column, the disposal form shows the selector, and the accountant-schedule CGT section gains a Method column ONLY when this flag is on — OFF keeps every payload/CSV byte-identical.
] as const;

export type FeatureKey = (typeof FEATURE_KEYS)[number];

function enabledSet(env: Env): Set<string> {
  return new Set(
    (env.FEATURES ?? "")
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean),
  );
}

/** True when `key` is listed in the FEATURES var. */
export function featureOn(env: Env, key: FeatureKey): boolean {
  return enabledSet(env).has(key);
}

/** The subset of known feature keys that are enabled — sent to the SPA so it can gate UI. */
export function enabledFeatures(env: Env): FeatureKey[] {
  const on = enabledSet(env);
  return FEATURE_KEYS.filter((k) => on.has(k));
}

/**
 * How statement categorisation should run. `live` = synchronous Claude calls (instant, full price);
 * `batch` = the async Message Batches API (~50% cheaper, applied by the cron); `auto` = today's
 * size-based routing (>BATCH_THRESHOLD lines → batch, else live). Resolution order, narrowest first:
 * per-tenant `profiles.categorise_mode` → env `CATEGORISE_MODE` → `auto`. Same single-call-site shape
 * as `featureOn`, so the per-tenant override lands with no churn at the call site (it already passes
 * the profile). An unrecognised value degrades safely to `auto`.
 */
export const CATEGORISE_MODES = ["auto", "live", "batch"] as const;
export type CategoriseMode = (typeof CATEGORISE_MODES)[number];

export function categoriseMode(env: Env, profile?: { categorise_mode?: string | null }): CategoriseMode {
  const raw = (profile?.categorise_mode ?? env.CATEGORISE_MODE ?? "auto").trim().toLowerCase();
  return (CATEGORISE_MODES as readonly string[]).includes(raw) ? (raw as CategoriseMode) : "auto";
}
